### ISSUE TITLE
Incompatible churn ruby_parser

### ISSUE THREAD

**Issue by ghost** [iain/metrical#7]
Thanks for metrical. Here's an error message I'm getting because metrical requires metric_fu, requires churn, requires an incompatible version of ruby_parser.

I've opened this issue with the churn author. Thanks, Joel (joel@sixarm.com)

Bundler could not find compatible versions for gem "ruby_parser":
  In Gemfile:
    metrical depends on
      ruby_parser (~> 2.0.4)

```
ruby_parser (2.3.0)
```

**Comment by iain** [comment]
_sigh_... Sometimes I think I should just lock down every dependency, all the way down.

Anyway, I couldn't reproduce the problem. The idea is that you don't add metrical to your Gemfile. After running `bundle install`, do a normal `gem install metrical` and all _should_ go well.

**Comment by SixArm** [comment]
Yes, I hear you. But the lock down is what's causing the problems.

A wiser solution imho is for gems to require versions using ranges, like  ">= 1.0.0", "<= 1.2.3"

This guarantees compatibility and enables more flexibility. 

It's fairly easy to do too because it's just a matter of running tests when a new version of a gem comes out.

**Comment by denikus** [comment]
Same problem

Bundler could not find compatible versions for gem "ruby_parser":
  In Gemfile:
    metrical (>= 0) ruby depends on
      ruby_parser (~> 2.0.4) ruby

```
ruby_parser (2.3.1)
```

Bundler could not find compatible versions for gem "json":
  In Gemfile:
    metrical (>= 0) ruby depends on
      json (= 1.6.1) ruby

```
cells (= 3.6.2) ruby depends on
  json (1.6.3)
```
